import CircleOutlined from '@mui/icons-material/CircleOutlined';
import ArrowDropDownRounded from '@mui/icons-material/ArrowDropDownRounded';
import ArrowDropUpRounded from '@mui/icons-material/ArrowDropUpRounded';
import {
  Alert,
  Box,
  Button,
  Card,
  CardContent,
  Checkbox,
  Dialog,
  DialogActions,
  DialogContent,
  DialogTitle,
  FormControlLabel,
  IconButton,
  Stack,
  Typography,
} from '@mui/material';
import { useMemo, useState } from 'react';
import { useAppState } from '../state/AppStateContext';

export const RoundsScreen = () => {
  const { state, assignTasksToRound, autoGroupTodayTasks, moveRound, showSuccessMessage } = useAppState();
  const [editingRoundId, setEditingRoundId] = useState<string | null>(null);
  const [selectedTaskIds, setSelectedTaskIds] = useState<string[]>([]);
  const todayKey = new Date().toISOString().slice(0, 10);
  const todaysTasks = useMemo(() => state.tasks.filter((task) => task.plannedDate === todayKey), [state.tasks, todayKey]);

  const editingRound = useMemo(
    () => state.rounds.find((round) => round.id === editingRoundId),
    [state.rounds, editingRoundId],
  );
  const totalSelectedMinutes = useMemo(
    () =>
      selectedTaskIds.reduce((total, taskId) => {
        const task = todaysTasks.find((candidate) => candidate.id === taskId);
        return total + (task?.estimateMinutes ?? 0);
      }, 0),
    [selectedTaskIds, todaysTasks],
  );

  const openRoundAssignment = (roundId: string) => {
    const round = state.rounds.find((item) => item.id === roundId);
    if (!round) return;
    setEditingRoundId(roundId);
    setSelectedTaskIds(round.taskIds);
  };

  const saveAssignment = () => {
    if (!editingRoundId) return;
    assignTasksToRound(editingRoundId, selectedTaskIds);
    showSuccessMessage('Round assignment saved.');
    setEditingRoundId(null);
    setSelectedTaskIds([]);
  };

  const availableTasks = useMemo(() => {
    return todaysTasks.filter((task) => !task.roundId || task.roundId === editingRound?.id);
  }, [todaysTasks, editingRound]);
  const unassignedTasks = useMemo(
    () => todaysTasks.filter((task) => !task.roundId || !state.rounds.some((round) => round.id === task.roundId)),
    [todaysTasks, state.rounds],
  );

  return (
    <Stack spacing={2}>
      <Box>
        <Typography variant="h3">Today's Rounds</Typography>
        <Typography color="text.secondary">Group today&apos;s tasks into rounds, then reorder rounds with the arrows.</Typography>
      </Box>
      <Box>
        <Button
          variant="outlined"
          onClick={() => {
            autoGroupTodayTasks();
            showSuccessMessage('Suggested rounds generated by category.');
          }}
        >
          Suggest groupings by category
        </Button>
      </Box>
      <Card sx={{ bgcolor: '#1a1a1a' }}>
        <CardContent>
          <Typography variant="h6" mb={1}>Unassigned today tasks</Typography>
          <Stack spacing={1}>
            {unassignedTasks.map((task) => (
              <Stack direction="row" spacing={1} alignItems="center" key={task.id}>
                <CircleOutlined fontSize="small" color="disabled" />
                <Typography>{task.title}</Typography>
              </Stack>
            ))}
            {unassignedTasks.length === 0 && (
              <Typography color="text.secondary">All today tasks are assigned to a round.</Typography>
            )}
          </Stack>
        </CardContent>
      </Card>
      {state.rounds.map((round) => (
        <Card key={round.id} sx={{ bgcolor: round.status === 'active' ? '#20201f' : '#1a1a1a' }}>
          <CardContent>
            <Stack direction="row" justifyContent="space-between" alignItems="center" mb={1}>
              <Typography variant="h5">{round.title} ({state.settings.pomodoroMinutes} min)</Typography>
              <Stack direction="row" spacing={0.25}>
                <IconButton size="small" onClick={() => moveRound(round.id, 'up')} aria-label={`move-round-up-${round.id}`}>
                  <ArrowDropUpRounded />
                </IconButton>
                <IconButton size="small" onClick={() => moveRound(round.id, 'down')} aria-label={`move-round-down-${round.id}`}>
                  <ArrowDropDownRounded />
                </IconButton>
              </Stack>
            </Stack>
            <Stack spacing={1} mb={2}>
              {round.taskIds.map((taskId) => {
                const task = todaysTasks.find((candidate) => candidate.id === taskId);
                if (!task) return null;
                return (
                  <Stack direction="row" spacing={1} alignItems="center" key={task.id}>
                    <CircleOutlined fontSize="small" color={task.status === 'done' ? 'success' : 'disabled'} />
                    <Typography>{task.title}</Typography>
                  </Stack>
                );
              })}
              {round.taskIds.length === 0 && <Typography color="text.secondary">No tasks assigned yet.</Typography>}
            </Stack>
            <Stack direction="row" spacing={1} flexWrap="wrap" useFlexGap>
              <Button variant="outlined" onClick={() => openRoundAssignment(round.id)}>
                Assign tasks
              </Button>
            </Stack>
          </CardContent>
        </Card>
      ))}
      <Dialog
        open={!!editingRound}
        onClose={() => setEditingRoundId(null)}
        fullWidth
        maxWidth="sm"
      >
        <DialogTitle>Assign tasks to {editingRound?.title}</DialogTitle>
        <DialogContent>
          <Stack mt={0.5}>
            {todaysTasks.length === 0 && (
              <Typography color="text.secondary">No tasks in today&apos;s list yet. Add from Task Bank first.</Typography>
            )}
            {availableTasks.length === 0 && todaysTasks.length > 0 && (
              <Typography color="text.secondary">All tasks are currently assigned to other rounds.</Typography>
            )}
            {availableTasks.map((task) => (
              <FormControlLabel
                key={task.id}
                control={(
                  <Checkbox
                    checked={selectedTaskIds.includes(task.id)}
                    onChange={(_, checked) =>
                      setSelectedTaskIds((current) =>
                        checked ? [...current, task.id] : current.filter((id) => id !== task.id),
                      )
                    }
                  />
                )}
                label={`${task.title} (${task.estimateMinutes} min)`}
              />
            ))}
          </Stack>
          {totalSelectedMinutes > state.settings.pomodoroMinutes && (
            <Alert severity="warning" sx={{ mt: 1 }}>
              Total selected time is {totalSelectedMinutes} min, which is above your recommended pomodoro length of{' '}
              {state.settings.pomodoroMinutes} min.
            </Alert>
          )}
        </DialogContent>
        <DialogActions>
          <Button onClick={() => setEditingRoundId(null)}>Cancel</Button>
          <Button variant="contained" onClick={saveAssignment}>Save assignment</Button>
        </DialogActions>
      </Dialog>
    </Stack>
  );
};
